general gui now supports python3
When trying to parse incomplete JSON messages, since python3 the ValueError exception is thrown with a slightly different text, we can now handle this as well.

$ python2 -c "import json; json.loads('{')"
ValueError: Expecting object: line 1 column 1 (char 0)

$ python3 -c "import json; json.loads('{')"
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)